# Interactive graph

<style>
    body {
      font-family: sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 200vh;
      margin: 0;
      margin-left: 20px; /* Adjust the left margin as needed */
      overflow: auto;
    }

    #plot {
      margin-top: 50px;
    }
    
    #content {
            max-width: 800px;
            text-align: justify;
            margin-bottom: 20px;
        }
  </style>

<div>

<h5>Select your region of interest:</h5>

<p></p>

<!-- Initialize a select button -->
<select id="selectButton"></select>
<p></p>

<!-- Create a div where the graph will take place -->

<div id="plot">
</div>

</div>

<div id="content">
<p>The presented graph illustrates the trends in health expenditure from 1995 to 2019, focusing on three key variables: Government Health Spending per person (in constant 2021 United States dollars), Prepaid Private Health Spending per person (in constant 2021 United States dollars), and Out-of-pocket Health Spending per person (in constant 2021 United States dollars). The graph employs a color-coded scheme, with government spending depicted in green, out-of-pocket spending in orange, and prepaid private spending in purple. Stacked bar charts provide a visual representation of how these financing sources contribute to overall health expenditure over the specified years.

To enhance your analysis, a dropdown menu is available for selecting a specific region of interest, allowing for a more focused examination of health spending patterns in a particular geographic area.

Upon examining health expenditure trends across different regions, several notable patterns emerge. Southeast Asia, East Asia, and Oceania exhibit a marked and swift increase in health spending over the observed years. In contrast, Sub-Saharan Africa maintains a remarkable consistency in its health expenditure trends, presenting a unique profile compared to other regions. Notably, North Africa and the Middle East experience a subtle decline in health spending from 2017 to 2019. What sets this region apart is the disproportionately large prevalence of prepaid private spending compared to out-of-pocket spending, diverging from global spending norms. In South Asia, a distinctive trend is the significant prominence of prepaid private spending compared to the global average. Conversely, in Central Europe, Eastern Europe, and Central Asia, a striking feature is the limited contribution of out-of-pocket spending, setting them apart from the broader global spending landscape. These nuanced observations unveil diverse and region-specific dynamics in health expenditure, offering valuable insights for further analysis and consideration. </p>
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>
